//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndex) DeepCopyInto(out *ElasticIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndex.
func (in *ElasticIndex) DeepCopy() *ElasticIndex {
	if in == nil {
		return nil
	}
	out := new(ElasticIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexLifecyclePolicies) DeepCopyInto(out *ElasticIndexLifecyclePolicies) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexLifecyclePolicies.
func (in *ElasticIndexLifecyclePolicies) DeepCopy() *ElasticIndexLifecyclePolicies {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexLifecyclePolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticIndexLifecyclePolicies) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexLifecyclePoliciesList) DeepCopyInto(out *ElasticIndexLifecyclePoliciesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticIndexLifecyclePolicies, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexLifecyclePoliciesList.
func (in *ElasticIndexLifecyclePoliciesList) DeepCopy() *ElasticIndexLifecyclePoliciesList {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexLifecyclePoliciesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticIndexLifecyclePoliciesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexLifecyclePoliciesSpec) DeepCopyInto(out *ElasticIndexLifecyclePoliciesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexLifecyclePoliciesSpec.
func (in *ElasticIndexLifecyclePoliciesSpec) DeepCopy() *ElasticIndexLifecyclePoliciesSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexLifecyclePoliciesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexLifecyclePoliciesStatus) DeepCopyInto(out *ElasticIndexLifecyclePoliciesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexLifecyclePoliciesStatus.
func (in *ElasticIndexLifecyclePoliciesStatus) DeepCopy() *ElasticIndexLifecyclePoliciesStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexLifecyclePoliciesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexList) DeepCopyInto(out *ElasticIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexList.
func (in *ElasticIndexList) DeepCopy() *ElasticIndexList {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexSpec) DeepCopyInto(out *ElasticIndexSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexSpec.
func (in *ElasticIndexSpec) DeepCopy() *ElasticIndexSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexStatus) DeepCopyInto(out *ElasticIndexStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexStatus.
func (in *ElasticIndexStatus) DeepCopy() *ElasticIndexStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexTemplate) DeepCopyInto(out *ElasticIndexTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexTemplate.
func (in *ElasticIndexTemplate) DeepCopy() *ElasticIndexTemplate {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticIndexTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexTemplateList) DeepCopyInto(out *ElasticIndexTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticIndexTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexTemplateList.
func (in *ElasticIndexTemplateList) DeepCopy() *ElasticIndexTemplateList {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticIndexTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexTemplateSpec) DeepCopyInto(out *ElasticIndexTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexTemplateSpec.
func (in *ElasticIndexTemplateSpec) DeepCopy() *ElasticIndexTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticIndexTemplateStatus) DeepCopyInto(out *ElasticIndexTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticIndexTemplateStatus.
func (in *ElasticIndexTemplateStatus) DeepCopy() *ElasticIndexTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticIndexTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
