# permissions for end users to edit elasticindextemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: elasticindextemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-operator
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: elasticindextemplate-editor-role
rules:
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindextemplates/status
  verbs:
  - get
