# permissions for end users to view elasticindexlifecyclepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: elasticindexlifecyclepolicies-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-operator
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: elasticindexlifecyclepolicies-viewer-role
rules:
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindexlifecyclepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindexlifecyclepolicies/status
  verbs:
  - get
