---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: demo-operator-system
rules:
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindexlifecyclepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindexlifecyclepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindexlifecyclepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindextemplates/finalizers
  verbs:
  - update
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindextemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindices/finalizers
  verbs:
  - update
- apiGroups:
  - elastic.test.com
  resources:
  - elasticindices/status
  verbs:
  - get
  - patch
  - update
