apiVersion: elastic.test.com/v1
kind: ElasticIndexLifecyclePolicies
metadata:
  labels:
    app.kubernetes.io/name: elasticindexlifecyclepolicies
    app.kubernetes.io/instance: elasticindexlifecyclepolicies-sample
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test-operator
  name: twitterilp
spec:
  name: "twitterilp"
  settings: |-
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_primary_shard_size": "5gb",
                "max_age": "1d"
              },
              "set_priority": {
                "priority": 100
              }
            }
          },
          "warm": {
            "min_age": "1d",
            "actions": {
              "readonly": {},
              "set_priority": {
                "priority": 50
              },
              "allocate": {
                "number_of_replicas": 0
              }
            }
          },
          "cold": {
            "min_age": "3d",
            "actions": {
              "readonly": {},
              "set_priority": {
                "priority": 0
              },
              "allocate": {
                "number_of_replicas": 0
              }
            }
          },
          "delete": {
            "min_age": "7d",
            "actions": {
              "delete": {
                "delete_searchable_snapshot": true
              }
            }
          }
        }
      }
    }'