apiVersion: elastic.test.com/v1
kind: ElasticIndex
metadata:
  labels:
    app.kubernetes.io/name: elasticindex
    app.kubernetes.io/instance: elasticindex-sample
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test-operator
  name: elasticindex-sample-twitter-0-0-4
spec:
  image: "nginx/test"
  size: 1
  name: "twitter0-0-4"
  settings: |-
    {
      "settings": {
        "index": {
          "number_of_shards": 3,  
          "number_of_replicas": 2 
        }
      }
    }

